ebook_metadata:
  title: ༄༅། །རྗེ་རྒོད་ཚང་པའི་རྣལ་འབྱོར་བཞིའི་ཟབ་འགྲེལ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། རྒོད་ཚང་པ།
  sku: LEK-MA-DK-02
  layers:
  - book_title
  - author
web_metadata:
  title:
    en: A Profound Commentary on the Four Yogas of Mahamudra
    bo: རྣལ་འབྱོར་བཞིའི་ཟབ་འགྲེལ་བཞུགས་སོ།།
  collection:
    en: Lekshey Ling Mahamudra Series–  Book 2
    bo: ལེགས་བཤད་གླིང་ཕྱག་རྒྱ་ཆེན་པོ།–  དེབ། ༢
  author:
    en: Gotsangpa
    bo: རྒོད་ཚང་པ།
  pusblisher:
    en: Lekshey Ling Publications
    bo: ཀརྨ་ལེགས་བཤད་གླིང།
  sku: LEK-MA-DK-02
  category:
    en: Mahamudra
    bo: ཕྱག་རྒྱ་ཆེན་པོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LEK-MA-DK-02.epub
  description:
    en: ''
    bo: ''
